// Regenerates notices.gen.ts from the repository's LICENSE and NOTICE.
// Run: node packages/app/src/licenses/build-notices.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "../../../..");
const read = (name) => fs.readFileSync(path.join(repoRoot, name), "utf8");

const output = `// Generated by build-notices.mjs from the repository's NOTICE and LICENSE. Do not edit.
export const upstreamNotice = ${JSON.stringify(read("NOTICE"))};

export const upstreamLicense = ${JSON.stringify(read("LICENSE"))};
`;

fs.writeFileSync(path.join(here, "notices.gen.ts"), output);
