import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import test from 'node:test';
import assert from 'node:assert/strict';
import {journal} from './journal.mjs';
function legacy(t){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'receiver-migrate-'))),file=dir+'/journal.sqlite';t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const db=new DatabaseSync(file);db.exec(`CREATE TABLE receiver_sessions(id TEXT PRIMARY KEY,request TEXT UNIQUE NOT NULL,task TEXT NOT NULL,creation TEXT NOT NULL,agent TEXT UNIQUE,cwd TEXT,phase TEXT NOT NULL,generation INTEGER NOT NULL DEFAULT 1,mode TEXT NOT NULL DEFAULT 'human',binding TEXT,native TEXT);CREATE TABLE receiver_intents(id TEXT PRIMARY KEY,session TEXT NOT NULL,body TEXT NOT NULL,state TEXT NOT NULL,consumed INTEGER NOT NULL DEFAULT 0,error TEXT);CREATE TABLE receiver_identity(id INTEGER PRIMARY KEY CHECK(id=1),controller TEXT NOT NULL,host TEXT NOT NULL);INSERT INTO receiver_sessions VALUES ('saved','create','task','{}','native-agent','/owned','created',3,'human',NULL,'provider-thread');INSERT INTO receiver_intents VALUES ('delivered','saved','{}','acknowledged',1,NULL);INSERT INTO receiver_identity VALUES (1,'controller','macbook');`);db.close();return file;}
const snapshot=db=>JSON.stringify(['receiver_sessions','receiver_intents','receiver_identity'].map(table=>db.prepare('SELECT * FROM '+table+' ORDER BY 1').all()));
test('additive completion migration preserves representative sessions, consumed sends and identity',t=>{const file=legacy(t),old=new DatabaseSync(file,{readOnly:true}),before=snapshot(old);old.close();for(let i=0;i<2;i++){const db=journal(file);assert.equal(snapshot(db),before);assert.equal(db.prepare('SELECT count(*) n FROM receiver_results').get().n,0);db.close();}});
test('older readers and rollback preserve original rows and optional completion checkpoints',t=>{const file=legacy(t),db=journal(file),before=snapshot(db);db.prepare('INSERT INTO receiver_results VALUES (?,?)').run('delivered','{"progress":{"cursor":{"epoch":"saved","seq":5}}}');db.close();const older=new DatabaseSync(file);assert.equal(snapshot(older),before);assert.equal(older.prepare('SELECT state,consumed FROM receiver_intents').get().consumed,1);older.close();const reopened=journal(file);assert.equal(snapshot(reopened),before);assert.equal(JSON.parse(reopened.prepare('SELECT value FROM receiver_results').get().value).progress.cursor.seq,5);reopened.close();});
test('read-only legacy observation never performs a hidden schema migration',t=>{const file=legacy(t),db=journal(file,true);assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE name='receiver_results'").get(),undefined);db.close();});
